In [2]:
import numpy as np
vector = np.arange(1, 11)
print(vector)

[ 1  2  3  4  5  6  7  8  9 10]


In [3]:
import numpy as np
m = np.zeros((3, 3), dtype=int)
print(m)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [5]:
import numpy as np
a = np.random.randint(1, 11, size=(5, 5))
print(a)

[[ 3  2 10  4  1]
 [ 1  3  3  6  2]
 [ 7  1  2  5  3]
 [ 8  9  7  7  3]
 [ 2  4  3  5  7]]


In [6]:
import numpy as np
a = np.random.rand(4, 4)
print(a)

[[0.62249446 0.5048349  0.46846719 0.92811496]
 [0.67770932 0.53303997 0.21916776 0.11879648]
 [0.32964736 0.05176519 0.68707937 0.80324049]
 [0.45516306 0.18105342 0.73909705 0.43038516]]


In [7]:
import numpy as np
a = np.random.randint(1, 11, size=5)
b = np.random.randint(1, 11, size=5)
addition = a + b
subtraction = a - b
multiplication = a * b
print(addition)
print(subtraction)
print(multiplication)

[ 5  3  6 12  8]
[ 3  1  0 -8 -6]
[ 4  2  9 20  7]


In [9]:
import numpy as np

a = np.random.rand(7)
b = np.random.rand(7)
print(np.dot(a, b))

1.9468223602177148


In [10]:
import numpy as np
a = np.random.randint(1, 11, size=(2, 2))
b = np.random.randint(1, 11, size=(2, 3))
c = np.dot(a, b)
print(c)

[[ 45  85 140]
 [ 18  44  52]]


In [11]:
import numpy as np
a = np.random.randint(1, 11, size=(3, 3))
a_inv = np.linalg.inv(a)
print(a_inv)

[[-0.11340206  0.30927835 -0.03092784]
 [ 0.40206186 -0.27835052 -0.07216495]
 [-0.31958763  0.1443299   0.18556701]]


In [12]:
import numpy as np
a = np.random.rand(4, 4)
print(a)
b = np.transpose(a)
print(b)

[[0.50836839 0.54631085 0.77676136 0.07212269]
 [0.26682777 0.79452438 0.31240283 0.49069637]
 [0.99685478 0.98881706 0.89813967 0.31590632]
 [0.63075235 0.39870116 0.90855909 0.44971904]]
[[0.50836839 0.26682777 0.99685478 0.63075235]
 [0.54631085 0.79452438 0.98881706 0.39870116]
 [0.77676136 0.31240283 0.89813967 0.90855909]
 [0.07212269 0.49069637 0.31590632 0.44971904]]


In [13]:
import numpy as np
a = np.random.randint(1, 11, size=(3, 4))
b = np.random.randint(1, 11, size=4)
c = np.dot(a, b)
print(c)

[196 122 134]


In [14]:
import numpy as np
a = np.random.rand(2, 3)
b = np.random.rand(3)
c = np.dot(a, b)
print(c)

[0.63252814 0.81584149]


In [15]:
import numpy as np
a = np.random.randint(1, 11, size=(2, 2))
b = np.random.randint(1, 11, size=(2, 2))
c = np.multiply(a, b)
print(c)

[[63  8]
 [24 21]]


In [16]:
import numpy as np
a = np.random.randint(1, 11, size=(2, 2))
b = np.random.randint(1, 11, size=(2, 2))
c = np.dot(a, b)
print(c)

[[75 45]
 [37 33]]


In [17]:
import numpy as np
a = np.random.randint(1, 101, size=(2, 2))
b = np.sum(a)
print(b)

211


In [19]:
import numpy as np
a = np.random.randint(1, 11, size=(4, 4))
b = np.random.randint(1, 11, size=(4, 4))
c = a - b
print(a)
print(b)
print(c)

[[ 1  5  9 10]
 [ 2  6  8  4]
 [ 2  6  1  7]
 [10  3  5  3]]
[[ 2  5  5  9]
 [ 4  4  4 10]
 [10  3  9 10]
 [ 1  5  4  3]]
[[-1  0  4  1]
 [-2  2  4 -6]
 [-8  3 -8 -3]
 [ 9 -2  1  0]]


In [20]:
import numpy as np
a = np.random.rand(3, 3)
b = np.sum(a, axis=1, keepdims=True)
print(a)
print(b)

[[0.54410082 0.46303424 0.93146752]
 [0.50209089 0.93666598 0.89953724]
 [0.79726918 0.64111478 0.35138397]]
[[1.93860258]
 [2.3382941 ]
 [1.78976793]]


In [22]:
import numpy as np
a = np.random.randint(1, 10, size=(3, 4))
b = a ** 2
print(a)
print(b)

[[8 1 2 2]
 [2 2 5 7]
 [4 6 9 1]]
[[64  1  4  4]
 [ 4  4 25 49]
 [16 36 81  1]]


In [23]:
import numpy as np
a = np.random.randint(1, 51, size=(4))
b = np.sqrt(a)
print(a)
print(b)

[11 48  3  8]
[3.31662479 6.92820323 1.73205081 2.82842712]


Завдання 2

In [24]:
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
a = arr % 2 != 0
arr[a] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [25]:
import numpy as np
a_1d = np.array([0, 1, 2, 3, 4, 5, 6, 7])
a_2d = a_1d.reshape(2, -1)
print(a_1d)
print(a_2d)

[0 1 2 3 4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]


In [26]:
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9], [10, 11, 12]])
c = np.vstack((a, b))
print(a)
print(b)
print(c)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [27]:
import numpy as np
a = np.array([1, 2, 3])
b = np.tile(a, 3)
c = np.repeat(b, 3)
print(c)

[1 1 1 2 2 2 3 3 3 1 1 1 2 2 2 3 3 3 1 1 1 2 2 2 3 3 3]


In [28]:
import numpy as np
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
c = np.intersect1d(a, b)
print(c)

[2 4]


In [2]:
import numpy as np
np.random.seed(100)
a = np.random.uniform(1,50, 20)
b = np.argsort(a)[-5:][::-1]
print(a)
print(b)

[27.62684215 14.64009987 21.80136195 42.39403048  1.23122395  6.95688692
 33.86670515 41.466785    7.69862289 29.17957314 44.67477576 11.25090398
 10.08108276  6.31046763 11.76517714 48.95256545 40.77247431  9.42510962
 40.99501269 14.42961361]
[15 10  3  7 18]


In [4]:
import numpy as np
a = np.array([1, 2, 3, np.nan, 5, 6, 7, np.nan])
mask = ~np.isnan(a)
filtered_a = a[mask]
print(filtered_a)

[1. 2. 3. 5. 6. 7.]


In [5]:
import numpy as np
a = np.array([1, 2, 3, 4, 5])
b = np.array([4, 5, 6, 7, 8])
c = np.linalg.norm(a - b)
print(c)

6.708203932499369


In [10]:
import numpy as np
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
b = np.where(x == 1)[0]
if len(b) >= 5:
    fifth_index = b[5]
    print(fifth_index)

10


In [11]:
import numpy as np
np.random.seed(100)
a = np.random.randint(0, 5, 10)
print("Input array:", a)
repeats = np.zeros(len(a), dtype=bool)
seen = {}
for i, value in enumerate(a):
    if value in seen:
        repeats[i] = True
    else:
        seen[value] = True
print("Output array:", repeats)


Input array: [0 0 3 0 2 4 2 2 2 2]
Output array: [False  True False  True False False  True  True  True  True]
